import type { Metadata } from "next";
import "./styles/main/main.scss";
import Dashboard from "./components/dashboard/dashboard";
import { ModalProvider } from "./components/modal/ModalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        <Dashboard />
        <ModalProvider>
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
